### ISSUE TITLE
MunitHelpers.Publications.run doesn't work on test reruns

### ISSUE THREAD

**Issue by savv** [tulip/munit-helpers#3]
Thanks for this library - finally I can test my publications!

One problem I noticed, is that rerunning the tests (by refreshing the tests page) gives the following error, because the collection from the previous run is still around:

MinimongoError: Duplicate _id 'txi72urGzEhPWjdpM'
    at MinimongoError (packages/minimongo/minimongo.js:44:1)
    at [object Object].LocalCollection.insert (packages/minimongo/minimongo.js:555:1)
    at Object.MunitHelpers.Auth.stubUser (packages/tulip_munit-helpers/common/auth.js:30:1)
    at Object.MunitHelpers.Connection.stubLogin (packages/tulip_munit-helpers/server/connection.js:71:1)
    at Object.MunitHelpers.Publications.runAsync (packages/tulip_munit-helpers/server/publications.js:46:1)
    at packages/tulip_munit-helpers/server/publications.js:23:1
    at packages/meteor/helpers.js:118:1
    at Object.MunitHelpers.Publications.run (packages/tulip_munit-helpers/server/publications.js:37:1)
    at Package (user-points-tests.js:10:29)
    at [object Object].func (packages/tinytest/tinytest.js:636:1)

**Comment by benweissmann** [comment]
You should use `MunitHelpers.Collections.stub` to stub out your collections so that they can be properly cleaned between test runs -- you can then call `MunitHelpers.restoreAll()` in your `setup` and `tearDown` functions. You'll need to call `restoreAll` in both places because of a [known bug in Munit](https://github.com/practicalmeteor/meteor-munit#known-issues)
