### ISSUE TITLE
MunitHelpers.Publications.run seems to break if the pub name, and the collection name are the same

### ISSUE THREAD

**Issue by savv** [tulip/munit-helpers#4]
I have a publication that counts stuff, similar the second example here:
http://docs.meteor.com/#/full/meteor_publish

If I name the publication the same as the collection, I get the following error:
Error: Internal server error [500]
    at Object.Future.wait (/Users/savvopoulos/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    at packages/meteor/helpers.js:119:1
    at Object.MunitHelpers.Publications.run (packages/tulip_munit-helpers/server/publications.js:37:1)
    at Package (user-points-tests.js:10:39)
    at [object Object].func (packages/tinytest/tinytest.js:636:1)
    at packages/tinytest/tinytest.js:406:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    - - - - -
    at meteorErrorFromMsg (packages/ddp-client/livedata_connection.js:1464:1)
    at [object Object]._.extend._livedata_nosub (packages/ddp-client/livedata_connection.js:1470:1)
    at onMessage (packages/ddp-client/livedata_connection.js:254:1)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at packages/meteor/dynamics_nodejs.js:123:1
    at packages/ddp-client/stream_client_nodejs.js:197:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at packages/ddp-client/stream_client_nodejs.js:196:1
    at packages/ddp-client/stream_client_nodejs.js:172:1

**Comment by benweissmann** [comment]
Hi savvopoulos,

I wasn't able to reproduce your issue. I added [a test](https://github.com/tulip/munit-helpers/commit/a161969bf4f8e524c59a006b7fd7b91319d09479#diff-b757e36de14b1783f0d310d93571f9ccR99) to the codebase to test this scenario, and it's passing.

Could you link to a minimal example that shows this error?

**Comment by savv** [comment]
I would have loved to, but it was ages ago.
